# Numpy

* NumPy is a Python library.

* NumPy is used for working with arrays.

* NumPy is short for "Numerical Python".

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,'s1','s2', 2+3, 3*1, {'name': 'vigo'}])

In [3]:
np1

array([1, 2, 3, 's1', 's2', 5, 3, {'name': 'vigo'}], dtype=object)

In [4]:
type(np1)

numpy.ndarray

In [5]:
np2 = np.array(list(range(1,80,)))

In [6]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [7]:
print(np.min(np2))

1


In [9]:
l1 = list(range(10,100,5))

In [10]:
l1

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [11]:
np.min(l1)

10

In [13]:
np2 = np.array([ [0,1,2], [2,4,5] ])

In [14]:
print(np2)

[[0 1 2]
 [2 4 5]]


In [15]:
print(l1)
print()
print(np1)
print()
print(np2)

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

[1 2 3 's1' 's2' 5 3 {'name': 'vigo'}]

[[0 1 2]
 [2 4 5]]


In [16]:
print(f'np1.shape() = {np1.shape}')

print(f'np2.shape() = {np2.shape}')

print(f'l1.shape() = {len(l1)}')

np1.shape() = (8,)
np2.shape() = (2, 3)
l1.shape() = 18


In [17]:
print(f'type(np1) = {type(np1)}   , np1. =dtype ={np1.dtype}')

type(np1) = <class 'numpy.ndarray'>   , np1. =dtype =object


In [18]:
print(f'type(np2) = {type(np2)}   , np2.dtype = {np2.dtype}')

type(np2) = <class 'numpy.ndarray'>   , np2.dtype = int32


In [19]:
np2

array([[0, 1, 2],
       [2, 4, 5]])

In [20]:
l2 = [[0,1,2],
      [2,4,5]]

l2

[[0, 1, 2], [2, 4, 5]]

In [21]:
l2[0][1] = 3
l2

[[0, 3, 2], [2, 4, 5]]

In [22]:
np2[0,1] = 3

np2

array([[0, 3, 2],
       [2, 4, 5]])

In [23]:
l2[0][1] = 'text'

l2

[[0, 'text', 2], [2, 4, 5]]

In [24]:
mt2 = np.arange(0,10,3)
mt2

array([0, 3, 6, 9])

In [25]:
mt2 = np.arange(10,100,5)

print(f'mt2 = {mt2}')

npRange = np.array(range(10,100,5))

print(f'npRange = {npRange}')

mt2 = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
npRange = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [27]:
mt3 = np.linspace(0,10,20)

print(mt3)
print(mt3.shape)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
(20,)


In [28]:
mt4 = np.random.rand(5,5)

print(mt4)

[[0.09785756 0.87182924 0.46853245 0.51095856 0.18465666]
 [0.40553289 0.62065103 0.59264307 0.94219296 0.35685156]
 [0.7400964  0.31039052 0.26309933 0.27998695 0.16665175]
 [0.20729107 0.69714232 0.27114397 0.02013839 0.66701209]
 [0.66557712 0.41046478 0.98193496 0.15077656 0.24090529]]
